export const fruitsData = [
  "Apple",
  "Banana",
  "Orange",
  "Mango",
  "Strawberry",
  "Pineapple",
  "Grapes",
  "Watermelon",
  "Blueberry",
  "Raspberry",
  "Peach",
  "Cherry",
  "Pear",
  "Plum",
  "Kiwi",
  "Papaya",
  "Guava",
  "Pomegranate",
  "Lemon",
  "Lime",
  "Cantaloupe",
  "Honeydew",
  "Fig",
  "Coconut",
  "Cranberry",
  "Blackberry",
  "Dragonfruit",
  "Lychee",
  "Tangerine",
  "Nectarine",
  "Apricot",
  "Mulberry",
  "Gooseberry",
  "Passionfruit",
  "Jackfruit",
  "Durian",
  "Avocado",
  "Starfruit",
  "Persimmon",
  "Rambutan",
  "Custard Apple",
  "Sapodilla",
  "Breadfruit",
  "Elderberry",
  "Boysenberry",
  "Quince",
  "Soursop",
  "Huckleberry",
  "Tamarind",
  "Jujube",
  "Marionberry",
  "Salak",
  "Yuzu",
  "Miracle Fruit",
  "Longan",
  "Santol",
  "Langsat",
  "Medlar",
  "Bilberry",
  "Barberry",
  "Feijoa",
  "Camu Camu",
  "Acerola",
  "Maqui",
  "Nance",
  "Lucuma",
  "Ackee",
  "Jabuticaba",
  "Mamoncillo",
  "Pawpaw",
  "Pepino",
  "Chokeberry",
  "Cloudberry",
  "Sea Buckthorn",
  "White Currant",
  "Red Currant",
  "Black Currant",
  "Rose Apple",
  "Mountain Papaya",
  "Yangmei",
  "Kumquat",
  "Finger Lime",
  "Calamansi",
  "Surinam Cherry",
  "Cupuacu",
  "Kei Apple",
  "Ceylon Gooseberry",
  "Desert Lime",
  "Indian Fig",
  "Cherimoya",
  "Bael",
  "Buddha's Hand",
  "Cactus Pear",
  "Indian Gooseberry",
  "Bignay",
  "Horned Melon",
  "Wood Apple",
  "Otaheite Gooseberry",
  "Ceylon Olive",
  "Soncoya",
  "Mammee Apple",
  "Velvet Apple",
];
